// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/User.proto

package com.henry.spring.redis;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:redis.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required string userName = 2;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>optional .redis.UserGroup userGroup = 3;</code>
     */
    boolean hasUserGroup();
    /**
     * <code>optional .redis.UserGroup userGroup = 3;</code>
     */
    com.henry.spring.redis.UserProtos.UserGroup getUserGroup();
    /**
     * <code>optional .redis.UserGroup userGroup = 3;</code>
     */
    com.henry.spring.redis.UserProtos.UserGroupOrBuilder getUserGroupOrBuilder();
  }
  /**
   * Protobuf type {@code redis.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:redis.User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              userName_ = bs;
              break;
            }
            case 26: {
              com.henry.spring.redis.UserProtos.UserGroup.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = userGroup_.toBuilder();
              }
              userGroup_ = input.readMessage(com.henry.spring.redis.UserProtos.UserGroup.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userGroup_);
                userGroup_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.henry.spring.redis.UserProtos.internal_static_redis_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.henry.spring.redis.UserProtos.internal_static_redis_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.henry.spring.redis.UserProtos.User.class, com.henry.spring.redis.UserProtos.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private java.lang.Object userName_;
    /**
     * <code>required string userName = 2;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERGROUP_FIELD_NUMBER = 3;
    private com.henry.spring.redis.UserProtos.UserGroup userGroup_;
    /**
     * <code>optional .redis.UserGroup userGroup = 3;</code>
     */
    public boolean hasUserGroup() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .redis.UserGroup userGroup = 3;</code>
     */
    public com.henry.spring.redis.UserProtos.UserGroup getUserGroup() {
      return userGroup_;
    }
    /**
     * <code>optional .redis.UserGroup userGroup = 3;</code>
     */
    public com.henry.spring.redis.UserProtos.UserGroupOrBuilder getUserGroupOrBuilder() {
      return userGroup_;
    }

    private void initFields() {
      id_ = 0L;
      userName_ = "";
      userGroup_ = com.henry.spring.redis.UserProtos.UserGroup.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasUserGroup()) {
        if (!getUserGroup().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, userGroup_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, userGroup_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.henry.spring.redis.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.henry.spring.redis.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.henry.spring.redis.UserProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.henry.spring.redis.UserProtos.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.henry.spring.redis.UserProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.henry.spring.redis.UserProtos.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.henry.spring.redis.UserProtos.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.henry.spring.redis.UserProtos.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.henry.spring.redis.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.henry.spring.redis.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.henry.spring.redis.UserProtos.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code redis.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:redis.User)
        com.henry.spring.redis.UserProtos.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.henry.spring.redis.UserProtos.internal_static_redis_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.henry.spring.redis.UserProtos.internal_static_redis_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.henry.spring.redis.UserProtos.User.class, com.henry.spring.redis.UserProtos.User.Builder.class);
      }

      // Construct using com.caseyscarborough.spring.redis.UserProtos.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserGroupFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (userGroupBuilder_ == null) {
          userGroup_ = com.henry.spring.redis.UserProtos.UserGroup.getDefaultInstance();
        } else {
          userGroupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.henry.spring.redis.UserProtos.internal_static_redis_User_descriptor;
      }

      public com.henry.spring.redis.UserProtos.User getDefaultInstanceForType() {
        return com.henry.spring.redis.UserProtos.User.getDefaultInstance();
      }

      public com.henry.spring.redis.UserProtos.User build() {
        com.henry.spring.redis.UserProtos.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.henry.spring.redis.UserProtos.User buildPartial() {
        com.henry.spring.redis.UserProtos.User result = new com.henry.spring.redis.UserProtos.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (userGroupBuilder_ == null) {
          result.userGroup_ = userGroup_;
        } else {
          result.userGroup_ = userGroupBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.henry.spring.redis.UserProtos.User) {
          return mergeFrom((com.henry.spring.redis.UserProtos.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.henry.spring.redis.UserProtos.User other) {
        if (other == com.henry.spring.redis.UserProtos.User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000002;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasUserGroup()) {
          mergeUserGroup(other.getUserGroup());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasUserName()) {
          
          return false;
        }
        if (hasUserGroup()) {
          if (!getUserGroup().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.henry.spring.redis.UserProtos.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.henry.spring.redis.UserProtos.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 2;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }

      private com.henry.spring.redis.UserProtos.UserGroup userGroup_ = com.henry.spring.redis.UserProtos.UserGroup.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.henry.spring.redis.UserProtos.UserGroup, com.henry.spring.redis.UserProtos.UserGroup.Builder, com.henry.spring.redis.UserProtos.UserGroupOrBuilder> userGroupBuilder_;
      /**
       * <code>optional .redis.UserGroup userGroup = 3;</code>
       */
      public boolean hasUserGroup() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .redis.UserGroup userGroup = 3;</code>
       */
      public com.henry.spring.redis.UserProtos.UserGroup getUserGroup() {
        if (userGroupBuilder_ == null) {
          return userGroup_;
        } else {
          return userGroupBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .redis.UserGroup userGroup = 3;</code>
       */
      public Builder setUserGroup(com.henry.spring.redis.UserProtos.UserGroup value) {
        if (userGroupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userGroup_ = value;
          onChanged();
        } else {
          userGroupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .redis.UserGroup userGroup = 3;</code>
       */
      public Builder setUserGroup(
          com.henry.spring.redis.UserProtos.UserGroup.Builder builderForValue) {
        if (userGroupBuilder_ == null) {
          userGroup_ = builderForValue.build();
          onChanged();
        } else {
          userGroupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .redis.UserGroup userGroup = 3;</code>
       */
      public Builder mergeUserGroup(com.henry.spring.redis.UserProtos.UserGroup value) {
        if (userGroupBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              userGroup_ != com.henry.spring.redis.UserProtos.UserGroup.getDefaultInstance()) {
            userGroup_ =
              com.henry.spring.redis.UserProtos.UserGroup.newBuilder(userGroup_).mergeFrom(value).buildPartial();
          } else {
            userGroup_ = value;
          }
          onChanged();
        } else {
          userGroupBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .redis.UserGroup userGroup = 3;</code>
       */
      public Builder clearUserGroup() {
        if (userGroupBuilder_ == null) {
          userGroup_ = com.henry.spring.redis.UserProtos.UserGroup.getDefaultInstance();
          onChanged();
        } else {
          userGroupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .redis.UserGroup userGroup = 3;</code>
       */
      public com.henry.spring.redis.UserProtos.UserGroup.Builder getUserGroupBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getUserGroupFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .redis.UserGroup userGroup = 3;</code>
       */
      public com.henry.spring.redis.UserProtos.UserGroupOrBuilder getUserGroupOrBuilder() {
        if (userGroupBuilder_ != null) {
          return userGroupBuilder_.getMessageOrBuilder();
        } else {
          return userGroup_;
        }
      }
      /**
       * <code>optional .redis.UserGroup userGroup = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.henry.spring.redis.UserProtos.UserGroup, com.henry.spring.redis.UserProtos.UserGroup.Builder, com.henry.spring.redis.UserProtos.UserGroupOrBuilder> 
          getUserGroupFieldBuilder() {
        if (userGroupBuilder_ == null) {
          userGroupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.henry.spring.redis.UserProtos.UserGroup, com.henry.spring.redis.UserProtos.UserGroup.Builder, com.henry.spring.redis.UserProtos.UserGroupOrBuilder>(
                  getUserGroup(),
                  getParentForChildren(),
                  isClean());
          userGroup_ = null;
        }
        return userGroupBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:redis.User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:redis.User)
  }

  public interface UserGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:redis.UserGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required string userGroupName = 2;</code>
     */
    boolean hasUserGroupName();
    /**
     * <code>required string userGroupName = 2;</code>
     */
    java.lang.String getUserGroupName();
    /**
     * <code>required string userGroupName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserGroupNameBytes();
  }
  /**
   * Protobuf type {@code redis.UserGroup}
   */
  public static final class UserGroup extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:redis.UserGroup)
      UserGroupOrBuilder {
    // Use UserGroup.newBuilder() to construct.
    private UserGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserGroup defaultInstance;
    public static UserGroup getDefaultInstance() {
      return defaultInstance;
    }

    public UserGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              userGroupName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.henry.spring.redis.UserProtos.internal_static_redis_UserGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.henry.spring.redis.UserProtos.internal_static_redis_UserGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.henry.spring.redis.UserProtos.UserGroup.class, com.henry.spring.redis.UserProtos.UserGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<UserGroup> PARSER =
        new com.google.protobuf.AbstractParser<UserGroup>() {
      public UserGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserGroup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int USERGROUPNAME_FIELD_NUMBER = 2;
    private java.lang.Object userGroupName_;
    /**
     * <code>required string userGroupName = 2;</code>
     */
    public boolean hasUserGroupName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string userGroupName = 2;</code>
     */
    public java.lang.String getUserGroupName() {
      java.lang.Object ref = userGroupName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userGroupName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userGroupName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserGroupNameBytes() {
      java.lang.Object ref = userGroupName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userGroupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0L;
      userGroupName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserGroupName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserGroupNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserGroupNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.henry.spring.redis.UserProtos.UserGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.henry.spring.redis.UserProtos.UserGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.henry.spring.redis.UserProtos.UserGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.henry.spring.redis.UserProtos.UserGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.henry.spring.redis.UserProtos.UserGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.henry.spring.redis.UserProtos.UserGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.henry.spring.redis.UserProtos.UserGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.henry.spring.redis.UserProtos.UserGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.henry.spring.redis.UserProtos.UserGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.henry.spring.redis.UserProtos.UserGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.henry.spring.redis.UserProtos.UserGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code redis.UserGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:redis.UserGroup)
        com.henry.spring.redis.UserProtos.UserGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.henry.spring.redis.UserProtos.internal_static_redis_UserGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.henry.spring.redis.UserProtos.internal_static_redis_UserGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.henry.spring.redis.UserProtos.UserGroup.class, com.henry.spring.redis.UserProtos.UserGroup.Builder.class);
      }

      // Construct using com.caseyscarborough.spring.redis.UserProtos.UserGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        userGroupName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.henry.spring.redis.UserProtos.internal_static_redis_UserGroup_descriptor;
      }

      public com.henry.spring.redis.UserProtos.UserGroup getDefaultInstanceForType() {
        return com.henry.spring.redis.UserProtos.UserGroup.getDefaultInstance();
      }

      public com.henry.spring.redis.UserProtos.UserGroup build() {
        com.henry.spring.redis.UserProtos.UserGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.henry.spring.redis.UserProtos.UserGroup buildPartial() {
        com.henry.spring.redis.UserProtos.UserGroup result = new com.henry.spring.redis.UserProtos.UserGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userGroupName_ = userGroupName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.henry.spring.redis.UserProtos.UserGroup) {
          return mergeFrom((com.henry.spring.redis.UserProtos.UserGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.henry.spring.redis.UserProtos.UserGroup other) {
        if (other == com.henry.spring.redis.UserProtos.UserGroup.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUserGroupName()) {
          bitField0_ |= 0x00000002;
          userGroupName_ = other.userGroupName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasUserGroupName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.henry.spring.redis.UserProtos.UserGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.henry.spring.redis.UserProtos.UserGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object userGroupName_ = "";
      /**
       * <code>required string userGroupName = 2;</code>
       */
      public boolean hasUserGroupName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string userGroupName = 2;</code>
       */
      public java.lang.String getUserGroupName() {
        java.lang.Object ref = userGroupName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userGroupName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userGroupName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserGroupNameBytes() {
        java.lang.Object ref = userGroupName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userGroupName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userGroupName = 2;</code>
       */
      public Builder setUserGroupName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userGroupName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userGroupName = 2;</code>
       */
      public Builder clearUserGroupName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userGroupName_ = getDefaultInstance().getUserGroupName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userGroupName = 2;</code>
       */
      public Builder setUserGroupNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userGroupName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:redis.UserGroup)
    }

    static {
      defaultInstance = new UserGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:redis.UserGroup)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_redis_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_redis_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_redis_UserGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_redis_UserGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/protobuf/User.proto\022\005redis\"I\n" +
      "\004User\022\n\n\002id\030\001 \002(\003\022\020\n\010userName\030\002 \002(\t\022#\n\tu" +
      "serGroup\030\003 \001(\0132\020.redis.UserGroup\".\n\tUser" +
      "Group\022\n\n\002id\030\001 \002(\003\022\025\n\ruserGroupName\030\002 \002(\t" +
      "B/\n!com.caseyscarborough.spring.redisB\nU" +
      "serProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_redis_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_redis_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_redis_User_descriptor,
        new java.lang.String[] { "Id", "UserName", "UserGroup", });
    internal_static_redis_UserGroup_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_redis_UserGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_redis_UserGroup_descriptor,
        new java.lang.String[] { "Id", "UserGroupName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
